### ISSUE TITLE
Components 'Display Range' and 'Ranged Curing' not installing

### ISSUE THREAD

**Issue by MikeX1234** [BartyMae/Bart_Tweaks#1]
I think, display_range.tpa and ranged_curing.tpa miss

`INCLUDE` `~bart_tweaks/lib/macros.tpa~`

at the beginning.

**Comment by BartyMae** [comment]
Wow, I am bad at noticing open issues on GitHub. Thanks, fixed the issue - if you use another component that already made use of the macros file (such as I would), then they would already be loaded and thus there'd be no issue, which is probably why I never noticed.
